### ISSUE TITLE
Can't start nginx after reinstall

### ISSUE THREAD

**Issue by louislang** [dperson/nginx#5]
I have been using this container for a while now. I recently reinstalled and, using the same command (via Ansible), I am unable to start the container. The command is as follows:

```
sudo docker run --name web -p 80:80 -p 443:443 --link vpn:transmission --link vpn:nzbget -d dperson/nginx -w "http://transmission:9091/transmission;/transmission" -w "http://nzbget:6789;/"
```

Like I said, this worked last week using this command. It seems when I grabbed the latest release it stopped working.

Is there a way for me to grab the logs to see what is happening?

**Comment by dperson** [comment]
My apologies, I was doing a little clean up and fat fingered it. _sigh_ It's fixed now.

**Comment by louislang** [comment]
Great! I wasn't sure if this was even an issue on my end. Thanks for getting to it so quickly!

**Comment by louislang** [comment]
Just got around to testing this out: Seems like I still can't start nginx. I got some logs: `nginx: [emerg] unknown "proxy_x_forwarded_proto" variable`. Is there something I need to do to grab the latest revision?

**Comment by dperson** [comment]
Have you done another `sudo docker pull dperson/nginx`? That will get you the latest version. Hope that helps.

**Comment by louislang** [comment]
Sure have. It shows that it's grabbing the latest, but the container refuses to start. I can provide logs if you'd like; the one I mentioned previously was all I could find though.

**Comment by dperson** [comment]
Could you please include both:
1. The full command line or docker-compose YAML that you're using to run the container.
2. The `docker logs <nginx_container_name>` output.

Thanks.

**Comment by louislang** [comment]
Sure.
**command line**
`sudo docker run --name web -p 80:80 -p 443:443 --link vpn:transmission --link vpn:nzbget -d dperson/nginx -w "http://transmission:9091/transmission;/transmission" -w "http://nzbget:6789;/"`

**docker logs**

```
Generating a 2048 bit RSA private key
..........................+++
.................................................+++
writing new private key to '/etc/nginx/ssl/privkey.pem'
-----
2016/03/30 03:54:52 [emerg] 1#1: unknown "proxy_x_forwarded_proto" variable
nginx: [emerg] unknown "proxy_x_forwarded_proto" variable
2016/03/30 03:54:58 [emerg] 1#1: unknown "proxy_x_forwarded_proto" variable
nginx: [emerg] unknown "proxy_x_forwarded_proto" variable
2016/03/31 01:01:22 [emerg] 1#1: unknown "proxy_x_forwarded_proto" variable
nginx: [emerg] unknown "proxy_x_forwarded_proto" variable
2016/03/31 01:01:42 [emerg] 1#1: unknown "proxy_x_forwarded_proto" variable
nginx: [emerg] unknown "proxy_x_forwarded_proto" variable
```

This worked previously, and I actually have this working on another machine (but I haven't updated that machine yet, so I'm not sure what revision it's currently running).

**Comment by dperson** [comment]
I don't see anything wrong with how you're launching it (there was a chance you were keeping the configuration in a volume and not reconfiguring on each run, so the typo would stay around). There have been 2 updates since the 1 version that had the typo you're hitting. My current version is below, do you see the same checksum?

```
dperson@tundro$ sudo docker ps -a | grep nginx
0acadcb30e72        dperson/nginx            "nginx.sh"               About a minute ago   Up 53 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                         docker_web_1
```

If for some reason a `sudo docker pull dperson/nginx` isn't working... How about removing the image entirely by running `sudo docker rmi -f dperson/nginx`. Then your docker daemon will have to fetch a new copy when you issue the run command again. Which also brings up, what version of docker are you running?

**Comment by louislang** [comment]
Yea for whatever reason `sudo docker pull dperson/nginx` wasn't updating the container. `sudo docker rmi` seemed to fix it though. The container seems to be running now! Thanks for the help!
